### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by Matt444** [msaw328/IO_car_detection#1]
1. Po wybraniu uszkodzonego pliku video program się zawiesza.
![image](https://user-images.githubusercontent.com/64275057/103821600-d24fc580-506e-11eb-8ace-07baaa3586ab.png)
2. Możliwość wyboru pliku niebędącego plikiem w obsługiwanym formacie. Sugerujemy aby ta opcja była zablokowana lub po wybraniu niepoprawnego formatu wyświetlany był błąd.
3. Słaba optymalizacja, bardzo długi czas analizy video.

**Comment by msaw328** [comment]
Wprowadziliśmy zmiany w kodzie, czy moglibyście spróbować odtworzyć te błędy?
Punktu 3 raczej niestety nie naprawimy.

**Comment by Matt444** [comment]
Wszystko działa ;)
